### ISSUE TITLE
pickling error recursive: deleting DB didn't help either

### ISSUE THREAD

**Issue by meetmangukiya** [errbotio/err-poll#4]
```
Traceback (most recent call last):
  File "/sub/deploy/.env/lib/python3.5/site-packages/errbot/core.py", line 453, in _execute_and_send
    reply = method(mess, match) if match else method(mess, args)
  File "/sub/deploy/data/plugins/errbotio/err-pollbot/poll.py", line 188, in vote
    return '%s:\n%s' % (current_poll, str(poll))
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/sub/deploy/.env/lib/python3.5/site-packages/errbot/storage/__init__.py", line 55, in mutable
    self._store.set(key, obj)
  File "/sub/deploy/.env/lib/python3.5/site-packages/errbot/storage/shelf.py", line 27, in set
    self.shelf[key] = value
  File "/usr/lib/python3.5/shelve.py", line 124, in __setitem__
    p.dump(value)
TypeError: can't pickle _gdbm.gdbm objects
```

**Comment by Vaelor** [comment]
I got the same error. Are you using the Mattermost Backend?
It happens in my case with the Mattermost Backend when the `!vote` command is issued trough a channel.
As a direct message it works.
I have not tested other Backends yet, but maybe that is an error with my Mattermost Backend and not with the plugin directly.

**Comment by meetmangukiya** [comment]
I'm getting it with gitter backed. I think the issue is not about backed
but the database that errbot is using. Does this look like a database
problem?

/CC @gbin

**Comment by zoni** [comment]
Do you get this only when using err-pollbot, or with other plugins as well?

**Comment by btotharye** [comment]
I have this same error on mattermost backend as well only in channels for some reason not direct messages.
